### ISSUE TITLE
Can i create Tabs?

### ISSUE THREAD

**Issue by AnderWoche** [pichlerer/fia901#3]
https://github.com/executablebooks/sphinx-tabs

**Comment by pichlerer** [comment]
Seems neat, but I wouldn't want to overcomplicate things. I'd say we use this when a specific use case arises.

**Comment by AnderWoche** [comment]
Ich möchte gerne Code beispiele auf Java, Kotlin, Python und mehr zeigen. Das Dokument wird dann richtig groß

**Comment by pichlerer** [comment]
Brauchen wir das denn? In der Prüfung und im Unterricht haben wir nur java benutzt.

**Comment by AnderWoche** [comment]
ja wir brauchen das

**Comment by AnderWoche** [comment]
Diese Dokumentation ist nicht nur für uns sondern für die ganze Welt und für unsere nachfahren

**Comment by pichlerer** [comment]
Ich denke das passt schon so. Das ist nur als Prüfungsvorbereitung gedacht

**Comment by AnderWoche** [comment]
Anzeige ist raus
